version: "3.9"

services:
  db:
    image: postgres:13.2
    env_file: .env.dev
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data/

  app:
    build: .
    env_file: .env.dev
    depends_on:
      - db

volumes:
  db-data:
