version: "3.9"

services:
  db:
    image: postgres:13.2
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data/
  app:
    build: .
    depends_on:
      - db

volumes:
  db-data:
