"""Add tables

Revision ID: 1ded0ba2147b
Revises:
Create Date: 2021-04-01 18:15:34.443004

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "1ded0ba2147b"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "Countries",
        sa.Column("CountryId", sa.Integer(), nullable=False),
        sa.Column("Name", sa.String(length=100), nullable=True),
        sa.Column("BaseUrl", sa.String(length=100), nullable=True),
        sa.Column("Latitude", sa.Float(precision=6), nullable=False),
        sa.Column("Longitude", sa.Float(precision=6), nullable=False),
        sa.PrimaryKeyConstraint("CountryId"),
    )
    op.create_table(
        "Regions",
        sa.Column("RegionId", sa.Integer(), nullable=False),
        sa.Column("CountryId", sa.Integer(), nullable=False),
        sa.Column("Name", sa.String(length=100), nullable=True),
        sa.Column("Latitude", sa.Float(precision=6), nullable=False),
        sa.Column("Longitude", sa.Float(precision=6), nullable=False),
        sa.ForeignKeyConstraint(
            ["CountryId"],
            ["Countries.CountryId"],
        ),
        sa.PrimaryKeyConstraint("RegionId"),
    )
    op.create_table(
        "Courses",
        sa.Column("CourseId", sa.Integer(), nullable=False),
        sa.Column("RegionId", sa.Integer(), nullable=False),
        sa.Column("Name", sa.String(length=100), nullable=False),
        sa.Column("Url", sa.String(length=200), nullable=False),
        sa.Column("Latitude", sa.Float(precision=6), nullable=False),
        sa.Column("Longitude", sa.Float(precision=6), nullable=False),
        sa.Column("Description", sa.String(length=2000), nullable=False),
        sa.ForeignKeyConstraint(
            ["RegionId"],
            ["Regions.RegionId"],
        ),
        sa.PrimaryKeyConstraint("CourseId"),
    )
    op.create_table(
        "Events",
        sa.Column("EventId", sa.Integer(), nullable=False),
        sa.Column("CourseId", sa.Integer(), nullable=False),
        sa.Column("RunSequenceNumber", sa.Integer(), nullable=False),
        sa.Column("Date", sa.String(length=10), nullable=False),
        sa.ForeignKeyConstraint(
            ["CourseId"],
            ["Courses.CourseId"],
        ),
        sa.PrimaryKeyConstraint("EventId"),
    )
    op.create_table(
        "Runs",
        sa.Column("RunId", sa.Integer(), nullable=False),
        sa.Column("EventId", sa.Integer(), nullable=False),
        sa.Column("ParkRunnerId", sa.String(length=50), nullable=False),
        sa.Column("Position", sa.Integer(), nullable=False),
        sa.Column("Hours", sa.Integer(), nullable=True),
        sa.Column("Minutes", sa.Integer(), nullable=True),
        sa.Column("Seconds", sa.Integer(), nullable=True),
        sa.Column("AgeCategory", sa.String(length=9), nullable=True),
        sa.Column("AgeGrade", sa.Float(precision=2), nullable=True),
        sa.Column("Gender", sa.String(length=1), nullable=True),
        sa.Column("GenderPosition", sa.Integer(), nullable=True),
        sa.Column("Note", sa.String(length=50), nullable=True),
        sa.ForeignKeyConstraint(
            ["EventId"],
            ["Events.EventId"],
        ),
        sa.PrimaryKeyConstraint("RunId"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("Runs")
    op.drop_table("Events")
    op.drop_table("Courses")
    op.drop_table("Regions")
    op.drop_table("Countries")
    # ### end Alembic commands ###
