"""Increase description length

Revision ID: cdeac4c3bfe3
Revises: 1ded0ba2147b
Create Date: 2021-04-10 19:01:17.850760

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "cdeac4c3bfe3"
down_revision = "1ded0ba2147b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "Courses",
        "Description",
        existing_type=sa.String(length=2000),
        type_=sa.String(length=8000),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "Courses",
        "Description",
        existing_type=sa.String(length=8000),
        type_=sa.String(length=2000),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
