"""Update country and course to match new JSON schema

Revision ID: f9c9905060d9
Revises: b3d4f9e41e8f
Create Date: 2021-06-19 09:16:26.232408

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "f9c9905060d9"
down_revision = "b3d4f9e41e8f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "country",
        sa.Column("bottom_left_latitude", sa.Float(precision=6), nullable=True),
    )
    op.add_column(
        "country",
        sa.Column("bottom_left_longitude", sa.Float(precision=6), nullable=True),
    )
    op.add_column(
        "country",
        sa.Column("top_right_latitude", sa.Float(precision=6), nullable=True),
    )
    op.add_column(
        "country",
        sa.Column("top_right_longitude", sa.Float(precision=6), nullable=True),
    )

    op.drop_column("country", "longitude")
    op.drop_column("country", "latitude")
    op.drop_column("country", "name")

    op.execute(
        """
        INSERT INTO country (
            id,
            base_url,
            bottom_left_latitude,
            bottom_left_longitude,
            top_right_latitude,
            top_right_longitude
        )
        VALUES (
            85,
            'www.parkrun.co.za',
            -34.589792,
            14.481783,
            -22.618415,
            32.27309
        )
    """
    )
    op.execute(
        """
        UPDATE course
        SET country_id = 85
    """
    )
    op.execute(
        """
        DELETE FROM country
        WHERE id = 21
    """
    )

    op.alter_column(
        "country",
        "bottom_left_latitude",
        existing_type=sa.Float(precision=6),
        nullable=False,
    )
    op.alter_column(
        "country",
        "bottom_left_longitude",
        existing_type=sa.Float(precision=6),
        nullable=False,
    )
    op.alter_column(
        "country",
        "top_right_latitude",
        existing_type=sa.Float(precision=6),
        nullable=False,
    )
    op.alter_column(
        "country",
        "top_right_longitude",
        existing_type=sa.Float(precision=6),
        nullable=False,
    )

    op.add_column(
        "course", sa.Column("localised_name", sa.String(length=100), nullable=True)
    )
    op.add_column("course", sa.Column("location", sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("course", "location")
    op.drop_column("course", "localised_name")
    op.add_column(
        "country",
        sa.Column("name", sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    )
    op.add_column(
        "country", sa.Column("latitude", sa.REAL(), autoincrement=False, nullable=False)
    )
    op.add_column(
        "country",
        sa.Column("longitude", sa.REAL(), autoincrement=False, nullable=False),
    )
    op.drop_column("country", "top_right_longitude")
    op.drop_column("country", "top_right_latitude")
    op.drop_column("country", "bottom_left_longitude")
    op.drop_column("country", "bottom_left_latitude")
    # ### end Alembic commands ###
